/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DocumentType = IDL.Variant({
  'cni' : IDL.Null,
  'other' : IDL.Null,
  'passport' : IDL.Null,
  'driver_license' : IDL.Null,
  'residence_permit' : IDL.Null,
});
export const ExtractedFields = IDL.Record({
  'nom' : IDL.Opt(IDL.Text),
  'numero_document' : IDL.Opt(IDL.Text),
  'date_naissance' : IDL.Opt(IDL.Text),
  'sexe' : IDL.Opt(IDL.Text),
  'nationalite' : IDL.Opt(IDL.Text),
  'adresse' : IDL.Opt(IDL.Text),
  'prenom' : IDL.Opt(IDL.Text),
  'lieu_naissance' : IDL.Opt(IDL.Text),
  'date_expiration' : IDL.Opt(IDL.Text),
  'date_delivrance' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const ScanSession = IDL.Record({
  'document_type' : DocumentType,
  'extracted' : ExtractedFields,
  'principal_key' : IDL.Text,
  'raw_json' : IDL.Text,
  'scanned_at' : Timestamp,
});
export const ScanRequest = IDL.Record({
  'document_type' : DocumentType,
  'image_base64' : IDL.Text,
});
export const OcrError = IDL.Variant({
  'network_error' : IDL.Text,
  'ocr_failure' : IDL.Text,
  'unsupported_document' : IDL.Null,
  'invalid_image' : IDL.Null,
});
export const ScanResult = IDL.Variant({ 'ok' : ScanSession, 'err' : OcrError });
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'clearLastScan' : IDL.Func([], [], []),
  'getLastScan' : IDL.Func([], [IDL.Opt(ScanSession)], ['query']),
  'scanDocument' : IDL.Func([ScanRequest], [ScanResult], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DocumentType = IDL.Variant({
    'cni' : IDL.Null,
    'other' : IDL.Null,
    'passport' : IDL.Null,
    'driver_license' : IDL.Null,
    'residence_permit' : IDL.Null,
  });
  const ExtractedFields = IDL.Record({
    'nom' : IDL.Opt(IDL.Text),
    'numero_document' : IDL.Opt(IDL.Text),
    'date_naissance' : IDL.Opt(IDL.Text),
    'sexe' : IDL.Opt(IDL.Text),
    'nationalite' : IDL.Opt(IDL.Text),
    'adresse' : IDL.Opt(IDL.Text),
    'prenom' : IDL.Opt(IDL.Text),
    'lieu_naissance' : IDL.Opt(IDL.Text),
    'date_expiration' : IDL.Opt(IDL.Text),
    'date_delivrance' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const ScanSession = IDL.Record({
    'document_type' : DocumentType,
    'extracted' : ExtractedFields,
    'principal_key' : IDL.Text,
    'raw_json' : IDL.Text,
    'scanned_at' : Timestamp,
  });
  const ScanRequest = IDL.Record({
    'document_type' : DocumentType,
    'image_base64' : IDL.Text,
  });
  const OcrError = IDL.Variant({
    'network_error' : IDL.Text,
    'ocr_failure' : IDL.Text,
    'unsupported_document' : IDL.Null,
    'invalid_image' : IDL.Null,
  });
  const ScanResult = IDL.Variant({ 'ok' : ScanSession, 'err' : OcrError });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'clearLastScan' : IDL.Func([], [], []),
    'getLastScan' : IDL.Func([], [IDL.Opt(ScanSession)], ['query']),
    'scanDocument' : IDL.Func([ScanRequest], [ScanResult], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };