/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DocumentType = { 'cni' : null } |
  { 'other' : null } |
  { 'passport' : null } |
  { 'driver_license' : null } |
  { 'residence_permit' : null };
export interface ExtractedFields {
  'nom' : [] | [string],
  'numero_document' : [] | [string],
  'date_naissance' : [] | [string],
  'sexe' : [] | [string],
  'nationalite' : [] | [string],
  'adresse' : [] | [string],
  'prenom' : [] | [string],
  'lieu_naissance' : [] | [string],
  'date_expiration' : [] | [string],
  'date_delivrance' : [] | [string],
}
export type OcrError = { 'network_error' : string } |
  { 'ocr_failure' : string } |
  { 'unsupported_document' : null } |
  { 'invalid_image' : null };
export interface ScanRequest {
  'document_type' : DocumentType,
  'image_base64' : string,
}
export type ScanResult = { 'ok' : ScanSession } |
  { 'err' : OcrError };
export interface ScanSession {
  'document_type' : DocumentType,
  'extracted' : ExtractedFields,
  'principal_key' : string,
  'raw_json' : string,
  'scanned_at' : Timestamp,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'clearLastScan' : ActorMethod<[], undefined>,
  'getLastScan' : ActorMethod<[], [] | [ScanSession]>,
  'scanDocument' : ActorMethod<[ScanRequest], ScanResult>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];