/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ScanSession {
    document_type: DocumentType;
    extracted: ExtractedFields;
    principal_key: string;
    raw_json: string;
    scanned_at: Timestamp;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type ScanResult = {
    __kind__: "ok";
    ok: ScanSession;
} | {
    __kind__: "err";
    err: OcrError;
};
export interface ScanRequest {
    document_type: DocumentType;
    image_base64: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type OcrError = {
    __kind__: "network_error";
    network_error: string;
} | {
    __kind__: "ocr_failure";
    ocr_failure: string;
} | {
    __kind__: "unsupported_document";
    unsupported_document: null;
} | {
    __kind__: "invalid_image";
    invalid_image: null;
};
export interface ExtractedFields {
    nom?: string;
    numero_document?: string;
    date_naissance?: string;
    sexe?: string;
    nationalite?: string;
    adresse?: string;
    prenom?: string;
    lieu_naissance?: string;
    date_expiration?: string;
    date_delivrance?: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum DocumentType {
    cni = "cni",
    other = "other",
    passport = "passport",
    driver_license = "driver_license",
    residence_permit = "residence_permit"
}
export interface backendInterface {
    clearLastScan(): Promise<void>;
    getLastScan(): Promise<ScanSession | null>;
    scanDocument(request: ScanRequest): Promise<ScanResult>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
}
import type { DocumentType as _DocumentType, ExtractedFields as _ExtractedFields, OcrError as _OcrError, ScanRequest as _ScanRequest, ScanResult as _ScanResult, ScanSession as _ScanSession, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearLastScan(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearLastScan();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearLastScan();
            return result;
        }
    }
    async getLastScan(): Promise<ScanSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLastScan();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLastScan();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async scanDocument(arg0: ScanRequest): Promise<ScanResult> {
        if (this.processError) {
            try {
                const result = await this.actor.scanDocument(to_candid_ScanRequest_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ScanResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.scanDocument(to_candid_ScanRequest_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ScanResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
}
function from_candid_DocumentType_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DocumentType): DocumentType {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_ExtractedFields_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExtractedFields): ExtractedFields {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OcrError_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OcrError): OcrError {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_ScanResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanResult): ScanResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ScanSession_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ScanSession): ScanSession {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ScanSession]): ScanSession | null {
    return value.length === 0 ? null : from_candid_ScanSession_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    document_type: _DocumentType;
    extracted: _ExtractedFields;
    principal_key: string;
    raw_json: string;
    scanned_at: _Timestamp;
}): {
    document_type: DocumentType;
    extracted: ExtractedFields;
    principal_key: string;
    raw_json: string;
    scanned_at: Timestamp;
} {
    return {
        document_type: from_candid_DocumentType_n4(_uploadFile, _downloadFile, value.document_type),
        extracted: from_candid_ExtractedFields_n6(_uploadFile, _downloadFile, value.extracted),
        principal_key: value.principal_key,
        raw_json: value.raw_json,
        scanned_at: value.scanned_at
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: [] | [string];
    numero_document: [] | [string];
    date_naissance: [] | [string];
    sexe: [] | [string];
    nationalite: [] | [string];
    adresse: [] | [string];
    prenom: [] | [string];
    lieu_naissance: [] | [string];
    date_expiration: [] | [string];
    date_delivrance: [] | [string];
}): {
    nom?: string;
    numero_document?: string;
    date_naissance?: string;
    sexe?: string;
    nationalite?: string;
    adresse?: string;
    prenom?: string;
    lieu_naissance?: string;
    date_expiration?: string;
    date_delivrance?: string;
} {
    return {
        nom: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.nom)),
        numero_document: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.numero_document)),
        date_naissance: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.date_naissance)),
        sexe: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.sexe)),
        nationalite: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.nationalite)),
        adresse: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.adresse)),
        prenom: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.prenom)),
        lieu_naissance: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.lieu_naissance)),
        date_expiration: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.date_expiration)),
        date_delivrance: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.date_delivrance))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ScanSession;
} | {
    err: _OcrError;
}): {
    __kind__: "ok";
    ok: ScanSession;
} | {
    __kind__: "err";
    err: OcrError;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ScanSession_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_OcrError_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    network_error: string;
} | {
    ocr_failure: string;
} | {
    unsupported_document: null;
} | {
    invalid_image: null;
}): {
    __kind__: "network_error";
    network_error: string;
} | {
    __kind__: "ocr_failure";
    ocr_failure: string;
} | {
    __kind__: "unsupported_document";
    unsupported_document: null;
} | {
    __kind__: "invalid_image";
    invalid_image: null;
} {
    return "network_error" in value ? {
        __kind__: "network_error",
        network_error: value.network_error
    } : "ocr_failure" in value ? {
        __kind__: "ocr_failure",
        ocr_failure: value.ocr_failure
    } : "unsupported_document" in value ? {
        __kind__: "unsupported_document",
        unsupported_document: value.unsupported_document
    } : "invalid_image" in value ? {
        __kind__: "invalid_image",
        invalid_image: value.invalid_image
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cni: null;
} | {
    other: null;
} | {
    passport: null;
} | {
    driver_license: null;
} | {
    residence_permit: null;
}): DocumentType {
    return "cni" in value ? DocumentType.cni : "other" in value ? DocumentType.other : "passport" in value ? DocumentType.passport : "driver_license" in value ? DocumentType.driver_license : "residence_permit" in value ? DocumentType.residence_permit : value;
}
function to_candid_DocumentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): _DocumentType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_ScanRequest_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ScanRequest): _ScanRequest {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    document_type: DocumentType;
    image_base64: string;
}): {
    document_type: _DocumentType;
    image_base64: string;
} {
    return {
        document_type: to_candid_DocumentType_n11(_uploadFile, _downloadFile, value.document_type),
        image_base64: value.image_base64
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DocumentType): {
    cni: null;
} | {
    other: null;
} | {
    passport: null;
} | {
    driver_license: null;
} | {
    residence_permit: null;
} {
    return value == DocumentType.cni ? {
        cni: null
    } : value == DocumentType.other ? {
        other: null
    } : value == DocumentType.passport ? {
        passport: null
    } : value == DocumentType.driver_license ? {
        driver_license: null
    } : value == DocumentType.residence_permit ? {
        residence_permit: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
